definitions:
  utils.Swagger:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/user/get:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: rows
        in: query
        name: rows
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ojbect
      summary: Get user
swagger: "2.0"
